[package]
name = "use-process-status"
description = "Primitive process status and outcome metadata for RustUse"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-process-status"
keywords = ["process", "status", "state", "outcome", "rustuse"]
categories = ["os", "data-structures"]

[dependencies]
use-process-id.workspace = true

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
