[package]
name = "use-process-id"
description = "Primitive process identity wrappers for RustUse"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-process-id"
keywords = ["process", "pid", "identity", "os", "rustuse"]
categories = ["os", "data-structures"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
