[package]
name = "use-os-family"
description = "Primitive operating system family vocabulary for RustUse"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-os-family"
keywords = ["os", "family", "platform", "unix", "rustuse"]
categories = ["os", "data-structures"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
